/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as IndicadoresRouteImport } from './routes/indicadores'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as FornecedoresIndexRouteImport } from './routes/fornecedores.index'
import { Route as EvaluationsIndexRouteImport } from './routes/evaluations.index'
import { Route as RequestsNewRouteImport } from './routes/requests.new'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as FornecedoresNewRouteImport } from './routes/fornecedores.new'
import { Route as FornecedoresIdRouteImport } from './routes/fornecedores.$id'
import { Route as EvaluationsNewRouteImport } from './routes/evaluations.new'
import { Route as EvaluationsIdRouteImport } from './routes/evaluations.$id'
import { Route as RequestsIdIndexRouteImport } from './routes/requests.$id.index'
import { Route as RequestsIdEditRouteImport } from './routes/requests.$id.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicadoresRoute = IndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresIndexRoute = FornecedoresIndexRouteImport.update({
  id: '/fornecedores/',
  path: '/fornecedores/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsIndexRoute = EvaluationsIndexRouteImport.update({
  id: '/evaluations/',
  path: '/evaluations/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsNewRoute = RequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresNewRoute = FornecedoresNewRouteImport.update({
  id: '/fornecedores/new',
  path: '/fornecedores/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedoresIdRoute = FornecedoresIdRouteImport.update({
  id: '/fornecedores/$id',
  path: '/fornecedores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsNewRoute = EvaluationsNewRouteImport.update({
  id: '/evaluations/new',
  path: '/evaluations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsIdRoute = EvaluationsIdRouteImport.update({
  id: '/evaluations/$id',
  path: '/evaluations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdIndexRoute = RequestsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RequestsIdRoute,
} as any)
const RequestsIdEditRoute = RequestsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RequestsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/indicadores': typeof IndicadoresRoute
  '/items': typeof ItemsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/evaluations/$id': typeof EvaluationsIdRoute
  '/evaluations/new': typeof EvaluationsNewRoute
  '/fornecedores/$id': typeof FornecedoresIdRoute
  '/fornecedores/new': typeof FornecedoresNewRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/evaluations/': typeof EvaluationsIndexRoute
  '/fornecedores/': typeof FornecedoresIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/requests/$id/': typeof RequestsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/indicadores': typeof IndicadoresRoute
  '/items': typeof ItemsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/evaluations/$id': typeof EvaluationsIdRoute
  '/evaluations/new': typeof EvaluationsNewRoute
  '/fornecedores/$id': typeof FornecedoresIdRoute
  '/fornecedores/new': typeof FornecedoresNewRoute
  '/requests/new': typeof RequestsNewRoute
  '/evaluations': typeof EvaluationsIndexRoute
  '/fornecedores': typeof FornecedoresIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/requests/$id': typeof RequestsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approvals': typeof ApprovalsRoute
  '/auth': typeof AuthRoute
  '/indicadores': typeof IndicadoresRoute
  '/items': typeof ItemsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/evaluations/$id': typeof EvaluationsIdRoute
  '/evaluations/new': typeof EvaluationsNewRoute
  '/fornecedores/$id': typeof FornecedoresIdRoute
  '/fornecedores/new': typeof FornecedoresNewRoute
  '/requests/$id': typeof RequestsIdRouteWithChildren
  '/requests/new': typeof RequestsNewRoute
  '/evaluations/': typeof EvaluationsIndexRoute
  '/fornecedores/': typeof FornecedoresIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/requests/$id/': typeof RequestsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approvals'
    | '/auth'
    | '/indicadores'
    | '/items'
    | '/reset-password'
    | '/evaluations/$id'
    | '/evaluations/new'
    | '/fornecedores/$id'
    | '/fornecedores/new'
    | '/requests/$id'
    | '/requests/new'
    | '/evaluations/'
    | '/fornecedores/'
    | '/requests/'
    | '/requests/$id/edit'
    | '/requests/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/approvals'
    | '/auth'
    | '/indicadores'
    | '/items'
    | '/reset-password'
    | '/evaluations/$id'
    | '/evaluations/new'
    | '/fornecedores/$id'
    | '/fornecedores/new'
    | '/requests/new'
    | '/evaluations'
    | '/fornecedores'
    | '/requests'
    | '/requests/$id/edit'
    | '/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approvals'
    | '/auth'
    | '/indicadores'
    | '/items'
    | '/reset-password'
    | '/evaluations/$id'
    | '/evaluations/new'
    | '/fornecedores/$id'
    | '/fornecedores/new'
    | '/requests/$id'
    | '/requests/new'
    | '/evaluations/'
    | '/fornecedores/'
    | '/requests/'
    | '/requests/$id/edit'
    | '/requests/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuthRoute: typeof AuthRoute
  IndicadoresRoute: typeof IndicadoresRoute
  ItemsRoute: typeof ItemsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EvaluationsIdRoute: typeof EvaluationsIdRoute
  EvaluationsNewRoute: typeof EvaluationsNewRoute
  FornecedoresIdRoute: typeof FornecedoresIdRoute
  FornecedoresNewRoute: typeof FornecedoresNewRoute
  RequestsIdRoute: typeof RequestsIdRouteWithChildren
  RequestsNewRoute: typeof RequestsNewRoute
  EvaluationsIndexRoute: typeof EvaluationsIndexRoute
  FornecedoresIndexRoute: typeof FornecedoresIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicadores': {
      id: '/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof IndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores/': {
      id: '/fornecedores/'
      path: '/fornecedores'
      fullPath: '/fornecedores/'
      preLoaderRoute: typeof FornecedoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/': {
      id: '/evaluations/'
      path: '/evaluations'
      fullPath: '/evaluations/'
      preLoaderRoute: typeof EvaluationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/new': {
      id: '/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof RequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores/new': {
      id: '/fornecedores/new'
      path: '/fornecedores/new'
      fullPath: '/fornecedores/new'
      preLoaderRoute: typeof FornecedoresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedores/$id': {
      id: '/fornecedores/$id'
      path: '/fornecedores/$id'
      fullPath: '/fornecedores/$id'
      preLoaderRoute: typeof FornecedoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/new': {
      id: '/evaluations/new'
      path: '/evaluations/new'
      fullPath: '/evaluations/new'
      preLoaderRoute: typeof EvaluationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations/$id': {
      id: '/evaluations/$id'
      path: '/evaluations/$id'
      fullPath: '/evaluations/$id'
      preLoaderRoute: typeof EvaluationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/': {
      id: '/requests/$id/'
      path: '/'
      fullPath: '/requests/$id/'
      preLoaderRoute: typeof RequestsIdIndexRouteImport
      parentRoute: typeof RequestsIdRoute
    }
    '/requests/$id/edit': {
      id: '/requests/$id/edit'
      path: '/edit'
      fullPath: '/requests/$id/edit'
      preLoaderRoute: typeof RequestsIdEditRouteImport
      parentRoute: typeof RequestsIdRoute
    }
  }
}

interface RequestsIdRouteChildren {
  RequestsIdEditRoute: typeof RequestsIdEditRoute
  RequestsIdIndexRoute: typeof RequestsIdIndexRoute
}

const RequestsIdRouteChildren: RequestsIdRouteChildren = {
  RequestsIdEditRoute: RequestsIdEditRoute,
  RequestsIdIndexRoute: RequestsIdIndexRoute,
}

const RequestsIdRouteWithChildren = RequestsIdRoute._addFileChildren(
  RequestsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuthRoute: AuthRoute,
  IndicadoresRoute: IndicadoresRoute,
  ItemsRoute: ItemsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EvaluationsIdRoute: EvaluationsIdRoute,
  EvaluationsNewRoute: EvaluationsNewRoute,
  FornecedoresIdRoute: FornecedoresIdRoute,
  FornecedoresNewRoute: FornecedoresNewRoute,
  RequestsIdRoute: RequestsIdRouteWithChildren,
  RequestsNewRoute: RequestsNewRoute,
  EvaluationsIndexRoute: EvaluationsIndexRoute,
  FornecedoresIndexRoute: FornecedoresIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
